### ISSUE TITLE
MODELO DE NEGOCIO WEB 2.0 

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-ggar#1]
[WEB 2.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-20-equipo-ggar/files/9668587/WEB.2.0.pdf)

**Comment by mel-16** [comment]
20% felicidades

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
